---
- hosts: localhost
  connection: local
  remote_user: root
  environment:
    LANG: "en_US.UTF-8"
  vars:
    erlang_version: 20.0
    elixir_version: 1.5.0
  tasks:
  - name: Build app deps
    shell: chdir=/app MIX_ENV=prod mix do local.hex --force, deps.get, deps.compile
  - name: Build app release
    shell: chdir=/app MIX_ENV=prod mix release --env=prod
