---
- hosts: localhost
  connection: local
  remote_user: root
  tasks:
  - name: Install dependencies
    yum: name={{item}} state=installed
    with_items:
      - ncurses-devel
      - openssl-devel
